[k8s_master]
master01    ansible_host=<public-dns>    ansible_user=ubuntu

[k8s_workers]
worker-red  ansible_host=<public-dns>    ansible_user=ubuntu
worker-blue ansible_host=<public-dns>    ansible_user=ubuntu

[k8s_cluster:children]
k8s_master
k8s_workers

[k8s_cluster:vars]
ansible_ssh_private_key_file=~/demo.pem
